### ISSUE TITLE
Issue when trying to run transcript_transformer in pretrain mode

### ISSUE THREAD

**Issue by NicolasProvencher** [TRISTAN-ORF/transcript_transformer#5]
Hi, 
Ive interested myself in trying to reproduce and play with transcript_transformer

So far I am trying to do different finetuning task with your pretrained model, since it doesnt seems like its avalaible I am trying to redo the pretraining according to whats in the read_me

So far i have run into 2 major issue that seems to stems from code added to make ribotie

First error was associated with name space issues which i fixed by adding these argument to my yml file
use_seq : True
out_prefix : null
cond : null
offsets : null
parallel : False

If not given there is a namespace error proccing for each of those arguments

Second error was in the setup step of you transcript_loader.py script
According to what I could understand, 
In the prepare_sets fonction when doing  mask_all = np.hstack(mask_set) since group_conds was empty because there are no ribo study in my h5 db the loop before did nothing and mask_set stayed empty so it crashed with an error

I made a fork of the project and fixed that part by adding a simple if else statement and it seem to work
Not sure if my fix will break something else somewhere else, I am not familiar with the entire codebase
i can do a pull request if you want

Just though Id share this
Cheers and congratulation on tis_transformer publication

Nicolas

**Comment by jdcla** [comment]
Hey Nicolas,

Thank you for pointing these items out. The transcript_transformer package was initially built to be a sandbox for me to play with and has eventually grown out to feature two major functionalities (tis_transformer and ribotie), which I have managed by creating dedicated scripts (tis_transformer.py, ribotie.py) to handle the majority of free parameters that are set based on the functionality and publication (these can also be found in `transcript_transformer/configs/ribotie_defaults.yml` and `transcript_transformer/configs/tis_transformer_defaults.yml`.

Today, I dont use the `transcript_transformer.py` script anymore, and the idea is that all major functionalities should be supported by either `tis_transformer.py` and `ribotie.py`. 

Can you specifically point out to me what you are trying to do (which model are you using?). I'm not sure what you mean with fine-tuning tis_transformer. Tis_transformer can be trained on custom data today, albeit it lacks a proper readme file still. You can explore this functionality by running the command `tis_transformer --help` in your terminal.

**Comment by jdcla** [comment]
I updated the tis_transformer README, which was necessary. Let me know whether this is the information you needed. thanks for the feedback!

**Comment by NicolasProvencher** [comment]
Oh right, somehow i still had the either the preprint or robotie in mind in which pretraining was nescessary, oups

In that case this should be easier than i though thanks
