### ISSUE TITLE
When extracting the ribosome data matrices via load_sparse or scipy; which row encodes which read_length?

### ISSUE THREAD

**Issue by Fredditeddy** [TRISTAN-ORF/transcript_transformer#7]
When having a:

exp_group = hdf[f'transcript/riboseq/{experiment}/5']

and succesfully extraced the ribosome matrix each of the matrices has the shape (tr_len*21).
As described the different rows decode the length of the according read. Which encodes which read_length?
And the value encodes the start of the read??

**Comment by jdcla** [comment]
Yes, read counts are by their 5' end of the read. The read lengths range from 20 to 40, as denoted by the hardcoded rule here: https://github.com/TRISTAN-ORF/transcript_transformer/blob/b842a36ed045176e691b5255b0b969d1b624c396/transcript_transformer/data.py#L144

**Comment by jdcla** [comment]
Almost, `transcript_matrix[20:0]` would be read length 40. Read length 41 is not included.
